<%@ include file="header.jsp" %>

<%--
<!-- <h1 class="title">Welcome to the public KISTI CA (Certificate Authority) web site.</h1>
<ul>
  <li>KISTI Certification Authority is operated by the Grid Technology Research Team of KISTI (Korea Institute of Science and Technology Information).</li>
  <li>The authority satisfies requirements from APGrid PMA.</li>
  <li>Certificate issues by the KISTI Grid CA are compatible with the Globus Toolkit middleware.</li>
  <br>
  <li>The public key cryptography is the basis of grid security architecture.</li>
  <li>Certification Authority(CA) is a mandatory componant of public key infrastructure(PKI).</li>
  <li>Please read <a href="http://www.globus.org/security/overview.html" target="_blank">"Overview of the Grid Security Infrastructure"</a> from Globus site.</li>
</ul>

<h2 class="title">Reference</h2>
<h2>Enroll</h2>
<ul>
    <li>Create Browser Certificate - Install a certificate in your web browser. This certificate may be exportable depending on browser and browser settings.</li>
    <li>Create Certificate from CSR -  Send a PKCS#10 certificate request generated by your server, and receive a certificate that can be installed on the server. Consult your server documentation.</li>
    <li>Create Keystore - Create a server generated keystore in PEM, PKCS#12 or JKS format and save to your disc. This keystore can be installed in a server, browser or in other applications.</li>
    <li>Create CV Certificate -  Used for EU EAC ePassport PKI. Send a CVC certificate request generated by an Inspection System, and receive a CV certificate. Note: this can not be used for regular certificates, CV certificates are completely different.</li>
    <% if(org.ejbca.config.WebConfiguration.getRenewalEnabled()) { %>
    <li>Renew Browser Certificate - Authenticate using a browser certificate and request it to be renewed. Requires client certificate authentication.</li>
    <% } %>
</ul>
<h2>Retrieve</h2>
<ul>
    <li>Fetch CA Certificates - Browse and download CA certificates.</li>
    <li>Fetch CA CRLs - Download Certificate Revocation Lists.</li>
    <li>Fetch User's Latest Certificate - Download the last issued certificate for a user for whom you know the certificate Distinguished Name.</li>
</ul>
<h2>Inspect</h2>
<ul>
    <li>Inspect certificate/CSR - Inspect a dump of a CSR or a certificate. This gives an output of a CVC or ASN.1 dump, suitable for technical inspection and debugging.</li>
</ul>
<h2>Miscellaneous</h2>
<ul>
    <li>List User's Certificates - List certificates for a user for whom you know the certificate Distinguished Name.</li>
    <li>Check Certificate Status - Check revocation status for a certificate where you know the Issuer Distinguished Name and the serial number.</li>
    <li>Administration - Go to the EJBCA Admin-GUI. Requires client certificate authentication.</li>  
    <% if (!"disabled".equalsIgnoreCase(org.ejbca.config.WebConfiguration.getDocBaseUri())) { %>
    <li>Documentation - Go to the on-line EJBCA documentation.</li>  
    <% } %>
</ul>  -->
--%>
 <!--====== PRELOADER PART START ======-->

 <div class="preloader">
  <div class="loader_34">
      <div class="ytp-spinner">
          <div class="ytp-spinner-container">
              <div class="ytp-spinner-rotator">
                  <div class="ytp-spinner-left">
                      <div class="ytp-spinner-circle"></div>
                  </div>
                  <div class="ytp-spinner-right">
                      <div class="ytp-spinner-circle"></div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>

<!--====== PRELOADER ENDS START ======-->

<!--====== HEADER PART START ======-->

<header id="home" class="header-area">
  <div class="navigation fixed-top">
      <div class="container">
          <div class="row">
              <div class="col-lg-12">
                  <nav class="navbar navbar-expand-lg">
                      <a class="navbar-brand" href="index.html">
                          <img src="assets/images/logo.png" alt="Logo" style="width: 3em;">
                      </a> <!-- Logo -->
                      <button class="navbar-toggler" type="button" data-toggle="collapse"
                          data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                          aria-expanded="false" aria-label="Toggle navigation">
                          <span class="toggler-icon"></span>
                          <span class="toggler-icon"></span>
                          <span class="toggler-icon"></span>
                      </button>

                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                          <ul class="navbar-nav ml-auto">
                              <li class="nav-item active"><a class="page-scroll" href="#home">Home</a></li>
                              <li class="nav-item"><a class="page-scroll" href="#about">KISTI CA</a></li>
                              <li class="nav-item"><a class="page-scroll" href="#service">GRID RESOURCES</a></li>
                              <li class="nav-item"><a class="page-scroll" href="#enroll">registration</a></li>
                              <li class="nav-item"><a class="page-scroll" href="#certificates">Certificates</a></li>
                              <li class="nav-item"><a class="page-scroll" href="#contact">Contact</a></li>
                              <li class="nav-item"><a class="page-scroll" href="#site">Reference</a></li>
                          </ul>
                      </div> <!-- navbar collapse -->
                  </nav> <!-- navbar -->
              </div>
          </div> <!-- row -->
      </div> <!-- container -->
  </div> <!-- navigation -->

  <div id="parallax" class="header-content d-flex align-items-center">
      <div class="header-shape shape-one layer" data-depth="0.10">
          <img src="assets/images/banner/shape/shape-1.png" alt="Shape">
      </div> <!-- header shape -->
      <div class="header-shape shape-tow layer" data-depth="0.30">
          <img src="assets/images/banner/shape/shape-2.png" alt="Shape">
      </div> <!-- header shape -->
      <div class="header-shape shape-three layer" data-depth="0.40">
          <img src="assets/images/banner/shape/shape-3.png" alt="Shape">
      </div> <!-- header shape -->
      <div class="header-shape shape-fore layer" data-depth="0.60">
          <img src="assets/images/banner/shape/shape-2.png" alt="Shape">
      </div> <!-- header shape -->
      <div class="header-shape shape-five layer" data-depth="0.20">
          <img src="assets/images/banner/shape/shape-1.png" alt="Shape">
      </div> <!-- header shape -->
      <div class="header-shape shape-six layer" data-depth="0.15">
          <img src="assets/images/banner/shape/shape-4.png" alt="Shape">
      </div> <!-- header shape -->
      <div class="header-shape shape-seven layer" data-depth="0.50">
          <img src="assets/images/banner/shape/shape-5.png" alt="Shape">
      </div> <!-- header shape -->
      <div class="header-shape shape-eight layer" data-depth="0.40">
          <img src="assets/images/banner/shape/shape-3.png" alt="Shape">
      </div> <!-- header shape -->
      <div class="header-shape shape-nine layer" data-depth="0.20">
          <img src="assets/images/banner/shape/shape-6.png" alt="Shape">
      </div> <!-- header shape -->
      <div class="header-shape shape-ten layer" data-depth="0.30">
          <img src="assets/images/banner/shape/shape-3.png" alt="Shape">
      </div> <!-- header shape -->
      <div class="container">
          <div class="row align-items-center">
              <div class="col-xl-5 col-lg-6">
                  <div class="header-content-right">
                      <h4 class="sub-title">Welcome,</h4>
                      <h1 class="title">KISTI CA</h1>
                      <p>(KISTI Certification Authority)</p>
                      <a class="main-btn" href="#request">REQUEST CERTIFICATES</a>
                  </div> <!-- header content right -->
              </div>
              <div class="col-lg-6 offset-xl-1">
                  <div class="header-image d-none d-lg-block">
                      <img src="assets/images/banner/kisti.png" alt="kisti">
                  </div> <!-- header image -->
              </div>
          </div> <!-- row -->
      </div> <!-- container -->
      <div class="header-social">
          <div class="container">
              <div class="row">
                  <div class="col-lg-12">
                      <div class="header-social-icon">
                          <ul>
                              <li><a href="#"><i class="lni-facebook-filled"></i></a></li>
                              <li><a href="#"><i class="lni-twitter-original"></i></a></li>
                              <li><a href="#"><i class="lni-behance-original"></i></a></li>
                              <li><a href="#"><i class="lni-linkedin-original"></i></a></li>
                          </ul>
                      </div> <!-- header social -->
                  </div>
              </div> <!-- row -->
          </div> <!-- container -->
      </div> <!-- header social -->
  </div> <!-- header content -->
</header>

<!--====== HEADER PART ENDS ======-->

<!--====== ABOUT PART START ======-->

<section id="about" class="about-area pt-125 pb-130">
  <div class="container">
      <div class="row justify-content-center">
          <div class="col-lg-12">
              <div class="section-title text-center">
                  <h2 class="title">KISTI CA</h2>
                  <p>KISTI Certification Authority is operated by the Grid Technology Research Team of KISTI</br>
                      The authority satisfies requirements from APGrid PMA <span class="emphasis">Asia Pacific Grid Policy Management Authority</span></br>
                      Certificate issues by the KISTI Grid CA are compatible with the Globus Toolkit middleware.
                  </p>
                  <p style="padding-top:2em">
                      The public key cryptography is the basis of grid security architecture.
                      <br>Certification Authority <span class="emphasis">CA</span> is a mandatory componant of 
                      public key infrastructure <span class="emphasis">PKI</span>.
                  </p>
              </div> <!-- section title -->
          </div>
      </div> <!-- row -->

      <div class="row text-justify">
          <div class="col-lg-4 col-md-6 col-sm-8">
              <div class="single-service text-center mt-30">
                  <div class="service-icon">
                      <i class="lni-users"></i>
                  </div>
                  <div class="service-content">
                      <h4 class="service-title"><a href="#">Enroll</a></h4>
                      <h2 class="counter-count" data-to="100" data-speed="1500">153</h2>
                      <p class="count-text">Total</p>
                  </div>
              </div> <!-- single service -->
          </div>
          <div class="col-lg-4 col-md-6 col-sm-8">
              <div class="single-service text-center mt-30">
                  <div class="service-icon">
                      <i class="lni-certificate"></i>
                  </div>
                  <div class="service-content">
                      <h4 class="service-title"><a href="#contact">Certificate</a></h4>
                      <h2 class="counter-count" data-to="100" data-speed="1500">253</h2>
                      <p>KISTI CA V4</p>
                  </div>
              </div> <!-- single service -->
          </div>
          <div class="col-lg-4 col-md-6 col-sm-8">
              <div class="single-service text-center mt-30">
                  <div class="service-icon">
                      <i class="lni-ban"></i>
                  </div>
                  <div class="service-content">
                      <h4 class="service-title"><a href="#">Revoked</a></h4>
                      <h2 class="counter-count" data-to="100" data-speed="1500">112</h2>
                      <p>KISTI CA V4</p>
                  </div>
              </div> <!-- single service -->
          </div>
      </div> <!-- row -->
      <div class="row">
          <div class="col-lg-6">
              <div class="about-content mt-10">
                  <ul class="clearfix">
                      <li>
                          <div class="single-info d-flex align-items-center">
                              <div class="info-icon">
                                  <i class="lni-calendar"></i>
                              </div>
                              <div class="info-text">
                                  <p><span class="main-btn-2">will be added current KISTI CA V4.0</span>
                                      <span class="badge badge-light" data-toggle="modal"
                                          data-target="#">details
                                      </span>
                                      : Apr, 2020 - </p>
                              </div>
                          </div>
                      </li>
                      <li>
                          <div class="single-info d-flex align-items-center">
                              <div class="info-icon">
                                  <i class="lni-folder"></i>
                              </div>
                              <div class="info-text">
                                  <p><span class="main-btn-2">CP/CPS </span>
                                      <span class="badge badge-light" data-toggle="modal"
                                          data-target="#">details
                                      </span>
                                  </p>
                              </div>
                          </div>
                      </li>
                  </ul>
              </div>
          </div>
          <div class="col-lg-6">
              <div class="about-content mt-10">
                  <ul class="clearfix">
                      <li>
                          <div class="single-info d-flex align-items-center">
                              <div class="info-icon">
                                  <i class="lni-calendar"></i>
                              </div>
                              <div class="info-text">
                                  <p><span class="main-btn-2">KISTI CA v3.0</span>
                                      <span class="badge badge-light" data-toggle="modal"
                                          data-target="#kisticav3">details</span>
                                      : Apr 14, 2017 - Apr 9, 2037 (for 20 years)</p>
                              </div>
                          </div> <!-- single info -->
                      </li>
                      <li>
                          <div class="single-info d-flex align-items-center">
                              <div class="info-icon">
                                  <i class="lni-calendar"></i>
                              </div>
                              <div class="info-text">
                                  <p><span>KISTI CA v2.0:</span>
                                      <span class="badge badge-light" data-toggle="modal"
                                          data-target="#kisticav2">details</span>
                                      Jul 12, 2007 - Aug 1, 2017 (for 20 years)</p>
                              </div>
                          </div> <!-- single info -->
                      </li>
                      <li>
                          <div class="single-info d-flex align-items-center">
                              <div class="info-icon">
                                  <i class="lni-calendar"></i>
                              </div>
                              <div class="info-text">
                                  <p><span>Production Level:</span>
                                      <span class="badge badge-light" data-toggle="modal"
                                          data-target="#productionLevel">details</span>
                                      Jun 1, 2004 - Nov 2006</p>
                              </div>
                          </div> <!-- single info -->
                      </li>
                      <li>
                          <div class="single-info d-flex align-items-center">
                              <div class="info-icon">
                                  <i class="lni-calendar"></i>
                              </div>
                              <div class="info-text">
                                  <p><span>Experimental version:</span> Mar 14, 2013</p>
                              </div>
                          </div> <!-- single info -->
                      </li>

                  </ul>
              </div>
          </div>

      </div>
      <!-- certificate modals -->
      <!-- KISTI CA V3.0 -->
      <div class="modal fade" id="kisticav3" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
          aria-hidden="true">
          <div class="modal-dialog" role="document">
              <div class="modal-content">
                  <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">KISTI CA v3.0</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                      </button>
                  </div>
                  <div class="modal-body">
                      <ul class="list-group list-group-flush">
                          <li class="list-group-item"><span class="lni-angle-double-right"> Subject: C=KR,
                                  O=KISTI, CN=KISTI Certification Authority</span></li>
                          <li class="list-group-item"><a class="lni-angle-double-right"
                                  href="http://ca.gridcenter.or.kr/certs/cps/KISTI-CA-CPCPS-3.0.pdf"
                                  target="_blank"> Certificate Policy and Certification Practice Statement (for
                                  v3.0)</a></li>
                          <li class="list-group-item"><span class="lni-angle-double-right"> Valid From: Apr 14,
                                  2017</span></li>
                          <li class="list-group-item"><span class="lni-angle-double-right"> Valid Until: Apr 9,
                                  2037 (for 20 years) </span></li>
                          <li class="list-group-item"><span class="lni-angle-double-right"> Key size: 4096
                                  bits</span></li>
                          <li class="list-group-item"><span class="lni-angle-double-right"> Download :</span>
                              <a href="http://ca.gridcenter.or.kr/certs/certificates/kisti-ca-v3.0"
                                  target="_blank"><u>kisti-ca-v3.0</u></a>
                              (<a href="http://ca.gridcenter.or.kr/certs/certificates/kisti-ca-v3.crt"
                                  target="_blank">.crt</a>)
                              (<a href="http://ca.gridcenter.or.kr/certs/certificates/kisti-ca-v3.txt"
                                  target="_blank">.txt</a>)
                              (<a href="http://ca.gridcenter.or.kr/certs/certificates/kisti-ca-v3.signing_policy"
                                  target="_blank"><u>signing_policy</u></a>)
                          </li>
                          <li class="list-group-item"><span class="lni-angle-double-right"> SHA256
                                  Fingerprint=CD:D6:F9:D8:39:75:94:29:71:6F:61:07:8E:77:91:A0:61:F7:42:B7:BE:72:CF:A9:CE:7C:E2:60:7F:5A:09:F1</span>
                          </li>
                          <li class="list-group-item"><span class="lni-angle-double-right"> SHA1
                                  Fingerprint=06:52:34:EE:81:0A:E5:9C:43:68:54:84:8C:8A:D4:DF:0D:75:A7:45</span>
                          </li>
                          <li class="list-group-item"><span class="lni-angle-double-right"> Issued Certificates <a
                                      href="http://ca.gridcenter.or.kr/issued_v3/" class="badge badge-light"
                                      target="_blank">list</a></span></li>
                          <li class="list-group-item"><span class="lni-angle-double-right"> CRL(Certificate
                                  Revocation List): <a
                                      href="http://ca.gridcenter.or.kr/CRL/kisti-ca-v3.crl">http://ca.gridcenter.or.kr/CRL/kisti-ca-v3.crl</a></span>
                          </li>
                      </ul>
                  </div>
                  <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  </div>
              </div>
          </div>
      </div>
      <!-- KISTI CA V2.0 -->
      <div class="modal fade" id="kisticav2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
          aria-hidden="true">
          <div class="modal-dialog" role="document">
              <div class="modal-content">
                  <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">KISTI CA v2.0</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                      </button>
                  </div>
                  <div class="modal-body">
                      <ul class="list-group list-group-flush">
                          <li class="list-group-item"><span class="lni-angle-double-right"> C=KR, O=KISTI, O=GRID,
                                  CN=KISTI Grid Certificate Authority</span></li>
                          <li class="list-group-item"><a class="lni-angle-double-right"
                                  href="http://ca.gridcenter.or.kr/cps/KISTI-CPCPS-2.0.html" target="_blank">
                                  Certificate Policy and Certification Practice Statement (for v2.0)</a></li>
                          <li class="list-group-item"><span class="lni-angle-double-right"> Valid From: Jul 12,
                                  2007</span></li>
                          <li class="list-group-item"><span class="lni-angle-double-right"> Valid Until: Aug 1,
                                  2017 (for 10 years) </span></li>
                          <li class="list-group-item"><span class="lni-angle-double-right"> Key size: 2048
                                  bits</span></li>
                          <li class="list-group-item"><span class="lni-angle-double-right"> Download :</span>
                              <a href="http://ca.gridcenter.or.kr/certs/certificates/722e5071.0"
                                  target="_blank"><u>722e5071.0</u></a>
                              (<a href="http://ca.gridcenter.or.kr/certs/certificates/722e5071.crt"
                                  target="_blank">.crt</a>)
                              (<a href="http://ca.gridcenter.or.kr/certs/certificates/722e5071.txt"
                                  target="_blank">.txt</a>)
                              (<a href="http://ca.gridcenter.or.kr/certs/certificates/722e5071.signing_policy"
                                  target="_blank"><u>signing_policy</u></a>)
                          </li>
                          <li class="list-group-item"><span class="lni-angle-double-right"> SHA256
                                  Fingerprint=EA:08:BA:6A:36:C9:F1:0A:B5:2F:BB:67:C7:A4:3D:C9:52:B7:CE:DB</span>
                          </li>
                          <li class="list-group-item"><span class="lni-angle-double-right"> SHA1
                                  Fingerprint=06:52:34:EE:81:0A:E5:9C:43:68:54:84:8C:8A:D4:DF:0D:75:A7:45</span>
                          </li>
                          <li class="list-group-item"><span class="lni-angle-double-right"> Issued Certificates <a
                                      href="http://ca.gridcenter.or.kr/issued/" class="badge badge-light"
                                      target="_blank">list</a></span></li>
                          <li class="list-group-item"><span class="lni-angle-double-right"> CRL(Certificate
                                  Revocation List): <a
                                      href="http://ca.gridcenter.or.kr/CRL/722e5071.crl">http://ca.gridcenter.or.kr/CRL/722e5071.crl</a></span>
                          </li>
                      </ul>
                  </div>
                  <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  </div>
              </div>
          </div>
      </div>
      <!-- Production Level -->
      <div class="modal fade" id="productionLevel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
          aria-hidden="true">
          <div class="modal-dialog" role="document">
              <div class="modal-content">
                  <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Production Level CA (June 1, 2004 - Nov.
                          2006)</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                      </button>
                  </div>
                  <div class="modal-body">
                      <ul class="list-group list-group-flush">
                          <li class="list-group-item"><span class="lni-angle-double-right"> Subject : C=KR,
                                  O=KISTI, CN=KISTI GRID ROOT CA</span></li>
                          <li class="list-group-item"><span class="lni-angle-double-right"> Valid until : May 30,
                                  2009 GMT </span></li>
                          <li class="list-group-item"><span class="lni-angle-double-right"> Key size: 2048
                                  bits</span></li>
                          <li class="list-group-item"><span class="lni-angle-double-right"> Download :</span>
                              <a href="http://ca.gridcenter.or.kr/certs/certificates/47183fda.0"
                                  target="_blank"><u>47183fda.0</u></a>
                              (<a href="http://ca.gridcenter.or.kr/certs/certificates/47183fda.txt"
                                  target="_blank">.txt</a>)
                              (<a href="http://ca.gridcenter.or.kr/certs/certificates/47183fda.signing_policy"
                                  target="_blank"><u>signing_policy</u></a>)
                          </li>
                          <li class="list-group-item"><span class="lni-angle-double-right"> CRL(Certificate
                                  Revocation List): <a
                                      href="http://ca.gridcenter.or.kr/CRL/47183fda.crl">http://ca.gridcenter.or.kr/CRL/47183fda.crl</a></span>
                          </li>
                      </ul>
                  </div>
                  <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  </div>
              </div>
          </div>
      </div>
  </div> <!-- container -->
</section>

<!--====== ABOUT PART ENDS ======-->

<!--====== SERVICES PART START ======-->

<section id="service" class="services-area gray-bg pt-125 pb-25">
  <div class="container">
      <div class="row justify-content-center">
          <div class="col-lg-8">
              <div class="section-title text-center pb-30">
                  <h2 class="title">GRID RESOURCES</h2>
                  <p>KISTI CA supports Grid Resource, such as ALICE, CMS, Belle II.</p>
              </div> <!-- section title -->
          </div>
      </div> <!-- row -->
      <div class="row justify-content-center">
          <div class="col-lg-4 col-md-6 col-sm-8">
              <div class="single-service text-center mt-30" style="height:320px;">
                  <div class="service-icon">
                      <img src="assets/images/service/alice.ico" style="width: 3em;" alt="ALICE"></img>
                  </div>
                  <div class="service-content">
                      <h4 class="service-title"><a href="https://home.cern/science/experiments/alice" target="_blank">ALICE</a></h4>
                      <p>A Large Ion Collider Experiment is a heavy-ion detector on the Large Hadron Collider <span class="emphasis">LHC</span> ring.</p>
                  </div>
              </div> <!-- single service -->
          </div>
          <div class="col-lg-4 col-md-6 col-sm-8">
              <div class="single-service text-center mt-30" style="height:320px;">
                  <div class="service-icon">
                      <img src="assets/images/service/cms.ico" style="width: 3em;" alt="CMS"></img>
                  </div>
                  <div class="service-content">
                      <h4 class="service-title"><a href="http://cms.web.cern.ch/" target="_blank">CMS</a></h4>
                      <p>Compact Muon Solenoid is a particle detector that is designed to see a wide range of particles 
                          and phenomena produced in high-energy collisions in the LHC <span class="emphasis">Large Hadron Collider</span>.</p>
                  </div>
              </div> <!-- single service -->
          </div>
          <div class="col-lg-4 col-md-6 col-sm-8">
              <div class="single-service text-center mt-30" style="height:320px;">
                  <div class="service-icon">
                      <img src="assets/images/service/belle2.ico" style="width: 3em;" alt="BELLE2"></img>
                  </div>
                  <div class="service-content">
                      <h4 class="service-title"><a href="https://www.belle2.org/project/super_kekb_and_belle_ii/">BELLE II</a></h4>
                      <p>The Belle experiment precisely analysed the characteristics of pairs of B- and anti-B-mesons and confirmed 
                          the effect of CP-violation.</p>
                  </div>
              </div> <!-- single service -->
          </div>
      
          <!-- <div class="col-lg-4 col-md-6 col-sm-8">
              <div class="single-service text-center mt-30">
                  <div class="service-icon">
                      <i class="lni-vector"></i>
                  </div>
                  <div class="service-content">
                      <h4 class="service-title"><a href="#">Illustration Design</a></h4>
                      <p>Curabitur vitae magna felis. Nulla ac libero ornare, vestibulum lacus quis blandit
                          enimdicta sunt.</p>
                  </div>
              </div> 
          </div>
          <div class="col-lg-4 col-md-6 col-sm-8">
              <div class="single-service text-center mt-30">
                  <div class="service-icon">
                      <i class="lni-website"></i>
                  </div>
                  <div class="service-content">
                      <h4 class="service-title"><a href="#">Web Development</a></h4>
                      <p>Curabitur vitae magna felis. Nulla ac libero ornare, vestibulum lacus quis blandit
                          enimdicta sunt.</p>
                  </div>
              </div> 
          </div>
          <div class="col-lg-4 col-md-6 col-sm-8">
              <div class="single-service text-center mt-30">
                  <div class="service-icon">
                      <i class="lni-support"></i>
                  </div>
                  <div class="service-content">
                      <h4 class="service-title"><a href="#">Consultancy and Support</a></h4>
                      <p>Curabitur vitae magna felis. Nulla ac libero ornare, vestibulum lacus quis blandit
                          enimdicta sunt.</p>
                  </div>
              </div> 
          </div>-->
      </div> 
  </div> <!-- container -->
</section>

<!--====== SERVICES PART ENDS ======-->


<!--====== CALL TO ACTION PART START ======-->

<section id="enroll" class="call-to-action pt-50 pb-25 bg_cover"
  style="background-image: url(assets/images/banner/gridcomputing3.png)">
  <div class="container">
      <div class="row justify-content-center">
          <div class="col-xl-8 col-lg-9">
              <div class="call-action-content text-center">
                  <!-- <h2 class="action-title">Will you be participating in the experiment above?</h2> -->
                  <h2 class="action-title">Do you need grid computing resources?</h2>
                  <p>Please Fill out the form below and contact the Registration Authority (RA) of your experiment community.
                  <br><i class="lni-envelope" style="padding-right:10px"></i><a class="page-scroll" href="#contact" style="color:#FFF"> Community mail list</a></p>
                  <ul>
                      <li><a class="main-btn custom" href="assets/docs/kisti_ca_user_form_v1.5.pdf" target="_blank"><i class="lni-download"></i>  Applicant</a></li>
                      <li><a class="main-btn custom-2" href="assets/docs/Personal_Information_Protection_Act.pdf" target="_blank"><i class="lni-download"></i>  Agreement</a></li>
                  </ul>
                  <p style="padding-left:200px"><i class="lni-pin-alt"></i> KOREAN only</p>
              </div> <!-- call action content -->
          </div>
      </div> <!-- row -->
  </div> <!-- container -->
</section>

<!--====== CALL TO ACTION PART ENDS ======-->



<!--====== CERTIFICATE PART START ======-->

<section id="certificates" class="certificate-area gray-bg pt-125 pb-130">
  <div class="container">
      <div class="row justify-content-center">
          <div class="col-lg-8">
              <div class="section-title text-center pb-25">
                  <h2 class="title">CERTIFICATES</h2>
                  <p>Nunc id dui at sapien faucibus fermentum ut vel diam. Nullam tempus, nunc id efficitur
                      sagittis, urna est ultricies eros, ac porta sem turpis quis leo.</p>
              </div> <!-- section title -->
          </div>
      </div> <!-- row -->
      <div class="row justify-content-center">
          <div class="col-lg-4 col-md-8 col-sm-9">
              <div class="single-certificate text-center mt-30">
                  <div class="certificate-package">
                      <h4 class="package-title">Enroll</h4>
                  </div>
                  <div class="certificate-body">
                      <div class="certificate-text">
                          <p>Create certificate or keystore</p>
                      </div>
                      <div class="certificate-list">
                          <ul>
                              <li>Create Browser Certificate</li>
                              <li>Create Certificate from CSR</li>
                              <li>Create Keystore</li>
                          </ul>
                      </div>
                      <div class="certificate-btn">
                          <a class="main-btn" href="#enroll-cert" data-toggle="modal" data-target="#enroll-cert"><i class="lni-enter"></i> go</a>
                      </div>
                  </div>
              </div> <!-- single certificate -->
          </div>
          <div class="col-lg-4 col-md-8 col-sm-9">
              <div class="single-certificate active text-center mt-30">
                  <div class="certificate-package">
                      <h4 class="package-title">Retrieve</h4>
                  </div>
                  <div class="certificate-body">
                      <div class="certificate-text">
                          <p>Fetch CA/User certificates</p>
                      </div>
                      <div class="certificate-list">
                          <ul style="text-align: left; margin-left: 3em;">
                              <li>Fetch CA Certificate</li>
                              <li>Fetch CA CRLs</li>
                              <li>List User's Certificates</li>
                              <li>Fetch User's Latest Certificate</li>
                          </ul>
                      </div>
                      <div class="certificate-btn">
                          <a class="main-btn" href="#contact">get quote</a>
                      </div>
                  </div>
              </div> <!-- single certificate -->
          </div>
          <div class="col-lg-4 col-md-8 col-sm-9">
              <div class="single-certificate text-center mt-30">
                  <div class="certificate-package">
                      <h4 class="package-title">Inspect</h4>
                  </div>
                  <div class="certificate-body">
                      <div class="certificate-text">
                          <p>Simple project management for teams and small businesses.</p>
                          <!-- <span class="price">$29.00</span> -->
                      </div>
                      <div class="certificate-list">
                          <ul>
                              <li>Inspect Certificate/CSR</li>
                              <li>Check Certificate Status</li>
                          </ul>
                      </div>
                      <div class="certificate-btn">
                          <a class="main-btn" href="#contact">get quote</a>
                      </div>
                  </div>
              </div> <!-- single certificate -->
          </div>
      </div> <!-- row -->

      <!-- Modal : Enroll Certificate  -->
      <div class="modal fade" id="enroll-cert" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
          aria-hidden="true">
          <div class="modal-dialog" role="document">
              <div class="modal-content">
                  <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Create Certificate </h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                      </button>
                  </div>
                  <div class="modal-body">
                      <ul class="list-group list-group-flush">
                          <li class="list-group-item"><span class="lni-angle-double-right" style="line-height: 20px;"> 
                              <a data-toggle="collapse" href="#browser-cert" role="button" aria-expanded="true"><b>Create Browser Certificate</b></a>
                              <br>Install a certificate in your web browser. This certificate may be exportable depending on browser and browser settings.</span></li>
                          <li class="list-group-item"><span class="lni-angle-double-right" style="line-height: 20px;"> 
                              <a data-toggle="collapse" href="#cert-from-csr" role="button" aria-expanded="true"><b>Create Certificate from CSR</b></a>
                              <br>Send a PKCS#10 certificate request generated by your server, and receive a certificate that can be installed on the server. Consult your server documentation.</span></li>
                          <li class="list-group-item"><span class="lni-angle-double-right" style="line-height: 20px;">
                              <a data-toggle="collapse" href="#keystore" role="button" aria-expanded="true"><b>Create Keystore</b></a>
                              <br>Create a server generated keystore in PEM, PKCS#12 or JKS format and save to your disc. This keystore can be installed in a server, browser or in other applications.</span></li>
                          <!-- <li class="list-group-item"><span class="lni-angle-double-right"> Download :</span>
                              <a href="http://ca.gridcenter.or.kr/certs/certificates/47183fda.0"
                                  target="_blank"><u>47183fda.0</u></a>
                              (<a href="http://ca.gridcenter.or.kr/certs/certificates/47183fda.txt"
                                  target="_blank">.txt</a>)
                              (<a href="http://ca.gridcenter.or.kr/certs/certificates/47183fda.signing_policy"
                                  target="_blank"><u>signing_policy</u></a>)
                          </li>
                          <li class="list-group-item"><span class="lni-angle-double-right"> CRL(Certificate
                                  Revocation List): <a
                                      href="http://ca.gridcenter.or.kr/CRL/47183fda.crl">http://ca.gridcenter.or.kr/CRL/47183fda.crl</a></span>
                          </li> -->
                      </ul>
                  </div>
                  <div class="collapse" id="browser-cert">
                      <div class="card card-body">
                        
                        <c:set var="THIS_TITLE" value="Certificate Enrollment" />
                        <jsp:useBean id="internalConfiguration" class="org.ejbca.config.InternalConfiguration" scope="request" />

                        <c:set var="THIS_FILENAME" value="/${internalConfiguration.appNameLowerDynamic}/enrol/browser.jsp" />
                        <c:set var="PASSWORD_TERMINOLOGY" value="enrollment_code" />
                        
                        <%@ include file="enroll/apply/apply_main.jsp" %>
                        
                      </div>
                  </div>
                  <div class="collapse" id="cert-from-csr">
                      <div class="card card-body">
                        create certificate from certificate
                      </div>
                  </div>
                  <div class="collapse" id="keystore">
                      <div class="card card-body">
                        create keystore
                      </div>
                  </div>
                  <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  </div>
              </div>
          </div>
      </div> <!-- Modal End: Enroll Certificate -->
  </div> <!-- container -->
</section>

<!--====== CERTIFICATE PART ENDS ======-->

<!--====== BLOG PART START ======-->

<section id="blog" class="blog-area pt-125 pb-130">
  <div class="container">
      <div class="row justify-content-center">
          <div class="col-lg-8">
              <div class="section-title text-center pb-25">
                  <h2 class="title">From The Blog</h2>
                  <p>Nunc id dui at sapien faucibus fermentum ut vel diam. Nullam tempus, nunc id efficitur
                      sagittis, urna est ultricies eros, ac porta sem turpis quis leo.</p>
              </div> <!-- section title -->
          </div>
      </div> <!-- row -->
      <div class="row justify-content-center">
          <div class="col-lg-4 col-md-8 col-sm-9">
              <div class="single-blog mt-30">
                  <div class="blog-image">
                      <img src="assets/images/blog/b-1.jpg" alt="Blog">
                  </div>
                  <div class="blog-content">
                      <h4 class="blog-title"><a href="#">Hired Releases 2023 Brand Health.</a></h4>
                      <span>July 26, 2022</span>
                  </div>
              </div> <!-- single blog -->
          </div>
          <div class="col-lg-4 col-md-8 col-sm-9">
              <div class="single-blog mt-30">
                  <div class="blog-image">
                      <img src="assets/images/blog/b-2.jpg" alt="Blog">
                  </div>
                  <div class="blog-content">
                      <h4 class="blog-title"><a href="#">Hired Releases 2023 Brand Health.</a></h4>
                      <span>July 26, 2022</span>
                  </div>
              </div> <!-- single blog -->
          </div>
          <div class="col-lg-4 col-md-8 col-sm-9">
              <div class="single-blog mt-30">
                  <div class="blog-image">
                      <img src="assets/images/blog/b-3.jpg" alt="Blog">
                  </div>
                  <div class="blog-content">
                      <h4 class="blog-title"><a href="#">Hired Releases 2023 Brand Health.</a></h4>
                      <span>July 26, 2022</span>
                  </div>
              </div> <!-- single blog -->
          </div>
      </div> <!-- row -->
      <div class="row">
          <div class="col-lg-12">
              <div class="blog-more text-center mt-50">
                  <a class="main-btn" href="#">More posts</a>
              </div> <!-- blog more -->
          </div>
      </div> <!-- row -->
  </div> <!-- container -->
</section>

<!--====== BLOG PART ENDS ======-->

<!--====== CONTACT PART START ======-->

<section id="contact" class="contact-area pt-125 pb-130 gray-bg">
  <div class="container">
      <div class="row justify-content-center">
          <div class="col-lg-8">
              <div class="section-title text-center pb-25">
                  <h2 class="title">Get In Touch</h2>
                  <p>Pleas Contact to RA <span class="emphasis">Registration Authority</span> at your community or university to enroll and
                      issue certificate.</p>
              </div> <!-- section title -->
          </div>
      </div> <!-- row -->
      <div class="row justify-content-center">
          <div class="col-lg-4 col-md-6 col-sm-7">
              <div class="contact-box text-center mt-30">
                  <div class="contact-icon">
                      <i class="lni-map-marker"></i>
                  </div>
                  <div class="contact-content">
                      <h6 class="contact-title">Address</h6>
                      <p>245, Daehak-ro, Yuseong-gu, Daejeon, Republic of Korea</p>
                  </div>
              </div> <!-- contact box -->
          </div>
          <div class="col-lg-4 col-md-6 col-sm-7">
              <div class="contact-box text-center mt-30">
                  <div class="contact-icon">
                      <i class="lni-phone"></i>
                  </div>
                  <div class="contact-content">
                      <h6 class="contact-title">Phone</h6>
                      <p>+82 42-869-0663</p>
                      <p>text</p>

                  </div>
              </div> <!-- contact box -->
          </div>
          <div class="col-lg-4 col-md-6 col-sm-7">
              <div class="contact-box text-center mt-30">
                  <div class="contact-icon">
                      <i class="lni-envelope"></i>
                  </div>
                  <div class="contact-content">
                      <h6 class="contact-title">Email</h6>
                      <p>kisti-grid-ca@kisti.re.kr</p>
                      <p>CA/RA mailing list at here</p>
                  </div>
              </div> <!-- contact box -->
          </div>
      </div> <!-- row -->
      <div class="row">
          <div class="col-lg-6">
              <div class="contact-form pt-30">
                  <form id="contact-form" action="assets/contact.php">
                      <div class="single-form">
                          <input type="text" name="name" placeholder="Name">
                      </div> <!-- single form -->
                      <div class="single-form">
                          <input type="email" name="email" placeholder="Email">
                      </div> <!-- single form -->
                      <div class="single-form">
                          <textarea name="message" placeholder="Message"></textarea>
                      </div> <!-- single form -->
                      <p class="form-message"></p>
                      <div class="single-form">
                          <button class="main-btn" type="submit">Send Message</button>
                      </div> <!-- single form -->
                  </form>
              </div> <!-- contact form -->
          </div>
          <div class="col-lg-6">
              <div class="contact-map mt-60">
                  <div class="gmap_canvas">
                      <iframe id="gmap_canvas"
                          src="https://maps.google.com/maps?q=Mission%20District%2C%20San%20Francisco%2C%20CA%2C%20USA&t=&z=13&ie=UTF8&iwloc=&output=embed"
                          frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
                  </div>
              </div> <!-- contact map -->
          </div>
      </div> <!-- row -->
  </div> <!-- container -->
</section>

<!--====== CONTACT PART ENDS ======-->

<%@ include file="footer.jsp" %>


<%@ include file="footer.jsp" %> -->



<!--container end-->



<!-- <h1 class="title">Welcome to the public KISTI CA (Certificate Authority) web site.</h1>
  <ul>
    <li>KISTI Certification Authority is operated by the Grid Technology Research Team of KISTI (Korea Institute of Science and Technology Information).</li>
    <li>The authority satisfies requirements from APGrid PMA.</li>
    <li>Certificate issues by the KISTI Grid CA are compatible with the Globus Toolkit middleware.</li>
    <br>
    <li>The public key cryptography is the basis of grid security architecture.</li>
    <li>Certification Authority(CA) is a mandatory componant of public key infrastructure(PKI).</li>
    <li>Please read <a href="http://www.globus.org/security/overview.html" target="_blank">"Overview of the Grid Security Infrastructure"</a> from Globus site.</li>
  </ul>

  <h2 class="title">Reference</h2>
  <h2>Enroll</h2>
  <ul>
	  <li>Create Browser Certificate - Install a certificate in your web browser. This certificate may be exportable depending on browser and browser settings.</li>
	  <li>Create Certificate from CSR -  Send a PKCS#10 certificate request generated by your server, and receive a certificate that can be installed on the server. Consult your server documentation.</li>
	  <li>Create Keystore - Create a server generated keystore in PEM, PKCS#12 or JKS format and save to your disc. This keystore can be installed in a server, browser or in other applications.</li>
	  <li>Create CV Certificate -  Used for EU EAC ePassport PKI. Send a CVC certificate request generated by an Inspection System, and receive a CV certificate. Note: this can not be used for regular certificates, CV certificates are completely different.</li>
      <% if(org.ejbca.config.WebConfiguration.getRenewalEnabled()) { %>
	  <li>Renew Browser Certificate - Authenticate using a browser certificate and request it to be renewed. Requires client certificate authentication.</li>
      <% } %>
  </ul>
  <h2>Retrieve</h2>
  <ul>
	  <li>Fetch CA Certificates - Browse and download CA certificates.</li>
	  <li>Fetch CA CRLs - Download Certificate Revocation Lists.</li>
	  <li>Fetch User's Latest Certificate - Download the last issued certificate for a user for whom you know the certificate Distinguished Name.</li>
  </ul>
  <h2>Inspect</h2>
  <ul>
	  <li>Inspect certificate/CSR - Inspect a dump of a CSR or a certificate. This gives an output of a CVC or ASN.1 dump, suitable for technical inspection and debugging.</li>
  </ul>
  <h2>Miscellaneous</h2>
  <ul>
	  <li>List User's Certificates - List certificates for a user for whom you know the certificate Distinguished Name.</li>
	  <li>Check Certificate Status - Check revocation status for a certificate where you know the Issuer Distinguished Name and the serial number.</li>
	  <li>Administration - Go to the EJBCA Admin-GUI. Requires client certificate authentication.</li>  
      <% if (!"disabled".equalsIgnoreCase(org.ejbca.config.WebConfiguration.getDocBaseUri())) { %>
	  <li>Documentation - Go to the on-line EJBCA documentation.</li>  
      <% } %>
  </ul>
<%@ include file="footer.inc" %> -->